name             'holberton-wrapper'
maintainer       'Rona Chong'
maintainer_email 'ronachong@gmail.com'
license          'All rights reserved'
description      'Installs/Configures holberton-wrapper'
long_description 'Installs/Configures holberton-wrapper'
version          '0.1.0'
